# Generated by Django 3.1.5 on 2021-01-22 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('image', models.ImageField(default='no-name.jpg', null=True, upload_to='Instructor')),
                ('department', models.CharField(max_length=30)),
                ('Experience', models.CharField(max_length=30)),
                ('Language', models.CharField(max_length=30)),
                ('About_Instructor', models.TextField()),
                ('Qualification', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Instructor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('percentage', models.IntegerField(default=0)),
                ('instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Instructor', to='instructor.instructor')),
            ],
        ),
    ]
