# Generated by Django 3.1.5 on 2021-01-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
