# Generated by Django 3.1.5 on 2021-01-22 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(default='no-name.jpg', null=True, upload_to='course')),
                ('price', models.IntegerField(blank=True, default=0)),
                ('discount_price', models.IntegerField(blank=True, default=0)),
                ('no_of_students', models.IntegerField(default=0)),
                ('lessons', models.CharField(max_length=100)),
                ('viewers', models.IntegerField(default=0)),
                ('duration', models.CharField(max_length=100)),
                ('feature_course', models.BooleanField(default=False)),
                ('prequisite', models.CharField(max_length=100)),
                ('certificate', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('assessments', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('what_will_i_learn', models.TextField()),
                ('learning_outcomes', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='courses.category')),
                ('instructor', models.ManyToManyField(to='instructor.Instructor')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Course_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_review', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_review_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course_Review',
                'verbose_name_plural': 'Course_Review',
            },
        ),
        migrations.CreateModel(
            name='Course_Curricularm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('subject', models.CharField(choices=[('Welcome_To_the_courses', 'Welcome To the courses'), ('How_to_use', 'How to use'), ('Final_chapters', 'Final chapters')], max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_curricularm', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course_Curricularm',
                'verbose_name_plural': 'Course_Curricularm',
            },
        ),
    ]
