# Generated by Django 3.1.5 on 2021-01-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210123_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_review',
            name='rating',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
